{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "project-operator.fullname" . }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: project-manager
      app.kubernetes.io/name: project-operator
  podMetricsEndpoints:
  - port: http
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
{{- end }}
